//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsRecord
    {
        public int sn { get; set; }
        public string UserId { get; set; }
        public int unitSn { get; set; }
        public Nullable<int> gameSn { get; set; }
        public Nullable<int> topicSn { get; set; }
        public Nullable<int> choiceSn { get; set; }
        public double assets { get; set; }
        public int type { get; set; }
        public System.DateTime inpdate { get; set; }
        public Nullable<int> h5forValue { get; set; }
        public Nullable<double> h5score { get; set; }
    }
}
