//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePosts
    {
        public int sn { get; set; }
        public int GameSn { get; set; }
        public Nullable<int> VedioRecordSn { get; set; }
        public int valid { get; set; }
        public System.DateTime inpdate { get; set; }
        public Nullable<int> TeamASn { get; set; }
        public Nullable<int> TeamBSn { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<int> PlayGameSn { get; set; }
        public Nullable<int> Synchronize { get; set; }
        public Nullable<int> Visited { get; set; }
        public string UserLive { get; set; }
        public Nullable<int> LiveCount { get; set; }
        public Nullable<int> AutoSn { get; set; }
    }
}
