//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Pay { get; set; }
        public string Order_No { get; set; }
        public string PayStore { get; set; }
        public string CodeNo { get; set; }
        public string PayerAccount5Code { get; set; }
        public string Barcode_3 { get; set; }
        public string Barcode_2 { get; set; }
        public string Barcode_1 { get; set; }
        public string PayBankCode { get; set; }
        public Nullable<System.DateTime> inpdate { get; set; }
    }
}
