//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Price { get; set; }
        public string ProductContent { get; set; }
        public Nullable<int> unitSn { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<byte> valid { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> inpdate { get; set; }
        public string image { get; set; }
        public Nullable<double> transform { get; set; }
        public string pdf_file { get; set; }
    }
}
