//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class choiceStr
    {
        public int sn { get; set; }
        public Nullable<int> unitSn { get; set; }
        public string choiceStr1 { get; set; }
        public int choiceSn { get; set; }
        public Nullable<int> trueCount { get; set; }
        public string eChoiceStr1 { get; set; }
    }
}
