//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public game()
        {
            this.betUnit = "1";
        }
    
        public int sn { get; set; }
        public Nullable<int> comSn { get; set; }
        public Nullable<int> userSn { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        public Nullable<byte> gameStatus { get; set; }
        public Nullable<byte> betModel { get; set; }
        public Nullable<byte> valid { get; set; }
        public Nullable<double> rake { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> modiDate { get; set; }
        public Nullable<System.DateTime> gamedate { get; set; }
        public string gameplace { get; set; }
        public string betUnit { get; set; }
        public Nullable<System.DateTime> payDate { get; set; }
        public Nullable<int> allocation { get; set; }
        public Nullable<int> live { get; set; }
    }
}
