//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class topicSetting
    {
        public int id { get; set; }
        public string topicsName { get; set; }
        public Nullable<bool> choiceType { get; set; }
        public Nullable<byte> valid { get; set; }
        public Nullable<int> gametype { get; set; }
        public string image { get; set; }
        public string hoverImage { get; set; }
        public Nullable<int> Model { get; set; }
        public string enName { get; set; }
        public Nullable<int> autotype { get; set; }
        public Nullable<double> numberType { get; set; }
    }
}
