//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class topic
    {
        public int sn { get; set; }
        public Nullable<int> comSn { get; set; }
        public Nullable<int> gameSn { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        public Nullable<double> totalmoney { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<byte> valid { get; set; }
        public Nullable<int> unitSn { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> modiDate { get; set; }
        public Nullable<bool> main { get; set; }
        public Nullable<double> outlay { get; set; }
        public Nullable<int> promote { get; set; }
        public Nullable<int> betnumber { get; set; }
        public string image { get; set; }
        public string hoverImage { get; set; }
        public Nullable<byte> walk { get; set; }
        public string etitle { get; set; }
        public Nullable<int> autotype { get; set; }
        public Nullable<double> numberType { get; set; }
    }
}
