//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRecord
    {
        public int id { get; set; }
        public string UserID { get; set; }
        public Nullable<int> unitSn { get; set; }
        public Nullable<double> assets { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> inpdate { get; set; }
        public Nullable<int> p_confirm { get; set; }
        public string recipient { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
    }
}
