//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferRecords
    {
        public int sn { get; set; }
        public string UserId { get; set; }
        public string Transfer { get; set; }
        public int unitSn { get; set; }
        public int type { get; set; }
        public double credit { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<double> rake { get; set; }
    }
}
